services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  metabase:
    image: metabase/metabase:latest
    container_name: ecommerce_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - ecommerce_network

  dbt:
    build:
      context: ./dbt_project
      dockerfile: Dockerfile
    container_name: ecommerce_dbt
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - ./dbt_project:/usr/app/dbt
    depends_on:
      - postgres
    networks:
      - ecommerce_network
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
networks:
  ecommerce_network:
    driver: bridge
