version: 2

models:
  - name: silver_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: silver_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values:
                - delivered
                - shipped
                - canceled
                - unavailable
                - invoiced
                - processing
                - created
                - approved

  - name: silver_order_items
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_products')
              field: product_id
      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_sellers')
              field: seller_id

  - name: silver_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: silver_sellers
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: silver_payments
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_orders')
              field: order_id
      - name: payment_value
        tests:
          - not_null

  - name: silver_order_reviews
    columns:
      - name: review_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_orders')
              field: order_id
      - name: review_score
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - review_id
            - order_id
